server:
  port: 1800
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置数据源
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置数据库连接属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reimg?characterEncoding=utf-8&serverTimezone=GMT%2B8&userSSL=false
    username: root
    password: 1234
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: MxchHikariPool
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 10s
        max-wait: 100
  thymeleaf:
    # 模板的模式
    mode: HTML5
    # 编码
    encoding: UTF-8
    # 开发配置为false，避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认为templates，可以不配置
    prefix: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      # 设置文件上传上限
      max-file-size: 50MB
      max-request-size: 100MB
mybatis-plus:
  configuration:
    # 添加日志支持
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml